### PR TITLE
Removing GPL license header from files.

### PR DESCRIPTION
**Pull request by MohammedKHC**
So after changing the license to MIT we should remove the GPL license header this PR removes it.

### CODE REVIEW

**Comment by MohammedKHC** [comment]
@Sydneycao  it looks like  you have contributed to the project. Do you agree to the license change??

See https://github.com/haodong404/codroid/commit/2c885fe8cdbd3558d49836d5c996abfad568f545

**Comment by MohammedKHC** [comment]
@haodong404 
Thank you very much for merging this.

Also i think that we should ask @Sydneycao if he agree to the license change.

Because he has contributed, See https://github.com/haodong404/codroid/commit/2c885fe8cdbd3558d49836d5c996abfad568f545

**Comment by haodong404** [comment]
Hi @MohammedKHC0 
That's ok, the commit https://github.com/haodong404/codroid/commit/2c885fe8cdbd3558d49836d5c996abfad568f545 is also made by me, but using a different GitHub account.

**Comment by MohammedKHC** [comment]
Make sense. Thank you very much for this project!

**Pull request merged**
